### ISSUE TITLE
Report with Saving plans

### ISSUE THREAD

**Issue by csdiedrich** [robsonbittencourt/aws-cost-miner#3]
Hello my friend,

We have in our AWS account the Saving Plans and Reserved Instance feature, when I run "EC2 COST REPORT" it returns the error attached, what am I doing wrong?
![cost_miner](https://user-images.githubusercontent.com/9849158/97988913-7f326b80-1dbc-11eb-9bbf-a7999b06ce4f.png)

**Comment by robsonbittencourt** [comment]
Hi 

aws-cost-miner did not have support for Saving Plans.

From your report, this was implemented in the latest version. Please update your image and test again, or use version 1.2.0.

Thank you for your report.
